### PR TITLE
Chef 11 compatible

### PR DESCRIPTION
**Pull request by secmff**
Using ubuntu 12.04 and chef 11, I had to change this to get it to work.

### CODE REVIEW

**Comment by phillmv** [comment]
Hey! Sorry to hear you had problems but also thanks for the pull request :D.

Quick question - what's up with the [provider line](https://github.com/appcanary/chef-appcanary/pull/1/files#diff-60bfb5066c3341ede8cc371d12094986R8)?

Not every platform we support uses upstart, so I'm weary of throwing that in. Is it possible to make it into an if-statement or check first somehow?

Thanks!

**Comment by gmacdougall** [comment]
Could you please split the upstart change out to a separate PR? I'm interested in the Chef 11 compatibility change.

**Comment by phillmv** [comment]
@gmacdougall is [this](https://github.com/secmff/chef-appcanary/commit/38adaae2f9cbc28ba8e60ce9a5e644f0dd33edbc) the only change it needs to be chef 11 compatible? I see no reason to not add that two line change in.

**Comment by gmacdougall** [comment]
@phillmv That's correct.

**Comment by phillmv** [comment]
Closed in lieu of #2

**Pull request closed without merging**
